### ISSUE TITLE
emojis in titles not working correctly

### ISSUE THREAD

**Issue by theoephraim** [docsifyjs/docsify#1009]
## Bug Report

Processing the emojis in titles isn't working correctly. Sometimes just turning it into a single ":" character. Seems to work correctly if no leading space before the emoji code.

#### Steps to reproduce

Insert this content in a page
```
#### :arrow_forward:  :arrow_forward:
#### :arrow_forward::arrow_forward:
#### &nbsp;:arrow_forward: :arrow_forward:
#### &nbsp;:arrow_forward::arrow_forward:
#### &nbsp;:arrow_forward:&nbsp;:arrow_forward:
```

#### What is current behaviour
![image](https://user-images.githubusercontent.com/1158956/72848269-3c126c00-3c72-11ea-8f7e-2bc61eb2e6d0.png)

#### What is the expected behaviour
All emojis should appear

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: mac
- Node.js version: 11.15
- npm/yarn version: 6.7
- Browser version: chrome latest
- Docsify version: cli is 4.4, using latest from cdn
- Docsify plugins: all disabled

**Comment by Koooooo-7** [comment]
@anikethsaha  
heyyyyy,  I investigated this bug, but it seems complicated for me.
so, I wanna share u to make it fixed possiblely.
I guess the issue is the **regex** of the function `getAndRemoveConfig ` at  [compile.js](https://github.com/docsifyjs/docsify/blob/develop/src/core/render/compiler.js#L22) 
```js
/(?:^|\s):([\w-]+)=?([\w-]+)?/g
```
I cheked the history of the function.
**FIRSTLY**, this function was applied for the [fix: zoom image plugin issue](https://github.com/docsifyjs/docsify/commit/fa772cfa94056e7f25b00d3f30a0c3604ae2d55e#diff-d73f215ac772d2673dd8c51f24976e4e) to get configurations about images. and it hadnt been called on the titles.

**THEN**, A new feature [feat: add heading config id](https://github.com/docsifyjs/docsify/commit/ab19b132107a5a92a9a99606ad637514ba616ebd#diff-d73f215ac772d2673dd8c51f24976e4e) called the function for the titles to get configurations. At the same time, there is the bug that the **regex** worked correctly to the title.

**NEXT**, the **regex** was updated once to fix one case [Fix getAndRemoveConfig regex](https://github.com/docsifyjs/docsify/pull/708) likes `# foo::bar::baz`.


Although, I tried to rewrite the regex ( a little bit hard for me ) or just keep the original title to be rendered to fix the bug, I thought the function should be separate for different places, or in anther way. beside that, the emojis have configuration  [noEmoji](https://docsify.js.org/#/configuration?id=noemoji) also.

**Comment by anikethsaha** [comment]
@Koooooo-7 thanks a lot for detailed investigation
What I am thinking is, 
as of now a regex to support all seem complicated, and it's hard for me as well to support the issues addressed here and in #708
I am proposing is to document this clearly that in order to support emojis, spaces are required at the beginning. 
We cant revert the #708 changes as it will break the site for Perl and other similar syntax-based lang.

**Comment by Koooooo-7** [comment]
@anikethsaha 
yep, I agree to make it clearly that how to support emojis at titles.
but I afraid that there is  a potential problem about  the `: ` of the title, configuration or emojis.

**Comment by anikethsaha** [comment]
> I afraid that there is a potential problem about the : of the title, configuration or emojis.

Can you mention some ?

**Comment by Koooooo-7** [comment]
@anikethsaha
A. the date `2020:02:02` is problem as u know.
B. Some titles with different spaces likes : 
```
### the news : my daily  :dog:
### the news :my daily  :dog:
### the news:my daily  :dog:
### the news: my daily  :dog:
```
All of them r not working correctly.

If possible, I think we need rewrite the feature [feat: add heading config id](https://github.com/docsifyjs/docsify/commit/ab19b132107a5a92a9a99606ad637514ba616ebd#diff-d73f215ac772d2673dd8c51f24976e4e) in another way that we dont through the `: ` to set and get configurations at the title.

**Comment by theoephraim** [comment]
I don't think trying to document this behaviour is going to work since it seems pretty unpredictable (look closely at the examples above).

Here's an idea - for the weird code syntax cases that #708 was trying to fix, require users to put  them within a code backticks to avoid any conflicting treatment from config or emojis, for example:
```
## `MyPerlModule::Submodule::function` :emoji: :id=something
```

**Comment by anikethsaha** [comment]
> another way that we dont through the : to set and get configurations at the title.

then what are you suggesting ? cause if you are thinking to consider other char, then I am pretty sure it will break other things or will give issues like #708 for other langs

**Comment by anikethsaha** [comment]
> Here's an idea - for the weird code syntax cases that #708 was trying to fix, require users to put them within a code backticks to avoid any conflicting treatment from config or emojis, for example:
> 
> ```
> ## `MyPerlModule::Submodule::function` :emoji: :id=something
> ```

It will render as code block like this

 ## `MyPerlModule::Submodule::function` :emoji: :id=something

It seems fine by me but I cant give assurance on behave of others.
@Koooooo-7 what do you think ?

**Comment by Koooooo-7** [comment]
this case  `## `MyPerlModule::Submodule::function` :emoji: :id=something` is not working correctly for me right now.

if it will render as u posted above, I think it is okay at now, but Idk how to document this clearly .

I think we may use `{}` likes`## Header {docsify-ignore}` contian the configurations to rewrite that feature instead.

**Comment by anikethsaha** [comment]
I think it wont render as I commented. it will be different. I need to look there.

> I think we may use {} likes## Header {docsify-ignore} contain the configurations to rewrite that feature instead.

lets have triple `{{{  }}}` as I think it's safe. cause Php has `{}` and mustache template lib has `{{ }}` too I think.

Anything else you think will fit here better ?

@trusktr , what do you think ?

**Comment by Koooooo-7** [comment]
I think the key is we can set the `prefix` to avoid conflict from others. such as `{docsify-id-myid}`.

**Comment by anikethsaha** [comment]
> I think the key is we can set the `prefix` to avoid conflict from others. such as `{docsify-id-myid}`.

+1 for this as well.

> Note :  any changes we make regarding this will be breaking change. I think it should be fit for `5.x`

Lets have a PoC for this.
Feel free to submit PoC to tackle this

**Comment by anikethsaha** [comment]
A better regex to support the current would be better if possible as it has fewer consequences of the change. 

Feel free to submit the better regex as well if possible
