### ISSUE TITLE
[NEXT] Docsify v5  

### ISSUE THREAD

**Issue by anikethsaha** [docsifyjs/docsify#1061]
### 4. [`Docsify-themeable`](https://jhildenbiddle.github.io/docsify-themeable/#/)
![status](https://img.shields.io/badge/Status-Ready%20to%20Implement-brightgreen) ![PR](https://img.shields.io/badge/PR-Welcome-green)

- From @jhildenbiddle 's comment in https://github.com/docsifyjs/docsify/issues/657#issuecomment-458341229

Docsify currently offers four official [themes](https://docsify.js.org/#/themes): vue, buble, dark, and pure. These themes are all more-or-less the same with the exception of a handful of basic style declarations (color, typography, margin/padding, etc). To make development easier, a CSS preprocessor (stylus) is used to compile each theme by combining a shared CSS file with a theme-specific CSS file. Makes sense.

Docsify-themeable takes a similar approach but offers a much more flexible implementation by leveraging CSS custom properties. The end-user pitch is available on the [introduction](https://jhildenbiddle.github.io/docsify-themeable/#/introduction) page, but the approach also provides advantages for docsify maintainers: a single block of CSS used for all themes, with each theme comprised of only a flat list of named values (e.g. `--sidebar-background: #ccc`) instead of  blocks of CSS. Legacy support is also available courtesy of [css-vars-ponyfill](https://www.npmjs.com/package/css-vars-ponyfill) (which I created specifically for docsify-themeable).

## Feedback/Suggestion/Recommending more changes

Feel free to leave feedback, and suggestion for the above features
Plus, Leave a comment if you want to add some more features. We can have a discussion about that.

cc @docsifyjs/cli @docsifyjs/contributors @docsifyjs/core

**Comment by QingWei-Li** [comment]
I can create a fresh PR if a new version starts develoment.

**Comment by anikethsaha** [comment]
> I can create a fresh PR if a new version starts development.

Coool. I guess that would fit best ! 💯

**Comment by alexellis** [comment]
I was impressed with the experience and how fast it was to make something useful -> https://docs.inlets.dev/, but I could really use a static generator to create HTML.

That means: getting permalinks and proper folders i..e /tutorials/k8s/that-one and being able to have the site scraped because it's rendering HTML and served from anywhere.

Looking forward to testing out the new release.

**Comment by anikethsaha** [comment]
Thanks for the heads up 💯 

> That means: getting permalinks and proper folders i..e /tutorials/k8s/that-one and being able to have the site scraped because it's rendering HTML and served from anywhere.

I do think we have a focus that includes this. 

> Looking forward to testing out the new release.

Though I can assure anyone when the work will begin and when it will be ready for release. 
But we will try to get it ASAP.
👍

**Comment by jhildenbiddle** [comment]
Happy to dive back in and help with the integration of docsify-themeable. I’m not sure what the timeline or preferred approach is though, so any guidance from the more active maintainers is welcome.

**Comment by anikethsaha** [comment]
> Happy to dive back in and help with the integration of docsify-themeable

Awesome

> I’m not sure what the timeline or preferred approach is though

I don't think there is any timeline as of now. about `docsify-themeable`, I am not familiar with the library so I think we can discuss that in gitter and proceed with your old approach which you planned.

**Comment by jhildenbiddle** [comment]
Sounds good, @anikethsaha.

**Comment by s-pace** [comment]
🎉 Do you want use to help you with search? I am part of the docsearch team https://docsearch.algolia.com/

**Comment by anikethsaha** [comment]
That would be really great to have it as official plugin or external.  Let me know how you would like to proceed . !

**Comment by s-pace** [comment]
Great. We will make sure to have the correct need:
- Server side rendering
-[ Sitemap.xml](https://docsearch.algolia.com/docs/config-file/#sitemaps)
- Proper html elements like `<article/>` to create a basic configuration
[- Promote it from our plugin page](https://docsearch.algolia.com/docs/integrations/#our-great-integrations)

All of theme will help the SEO too

**Comment by anikethsaha** [comment]
> * Server side rendering
>   -[ Sitemap.xml](https://docsearch.algolia.com/docs/config-file/#sitemaps)

With plugins we cant do this but we can add a section in our docs.


> * Proper html elements like `<article/>` to create a basic configuration
>   [- Promote it from our plugin page](https://docsearch.algolia.com/docs/integrations/#our-great-integrations)

it can be with plugin

**Comment by s-pace** [comment]
What is the default elements used then instead of `<article/>` ? We would need some steady class otherwise.

**Comment by anikethsaha** [comment]
the current search bar is placed in sidebar which is placed in `aside`. You can check the code for current search plugin [here](https://github.com/docsifyjs/docsify/tree/develop/src/plugins/search).

- Sidebar is in `aside` with `.sidebar` class (steady)
- the main content is placed in `section.content` . (steady)
- Navbar in `nav.app-nav`. 

If you want to keep the search bar in position where the current one is placed, I think that may not be the clear and complete visibility space for the search result. 

This is the current search results

![image](https://user-images.githubusercontent.com/26347874/78140383-8e78c180-7447-11ea-8524-3283dc5cfb1b.png)

so either you can bring our the search result or place the search bar at the top in the navbar . 

I think its better to be in navbar and  we can take `docusaurus@2`'s  sidebar + navbar layout for reference

**Comment by anikethsaha** [comment]
Also, we will remove the current dark mode button and it will be added through the core in the navbar

**Comment by s-pace** [comment]
Glad to ear.

We are working on an amazing new discovery experience with the search so stay tuned (Spoiler, @francoischalifour and @shipow are on 🔥) .

I will be happy to help on that and make the process really smooth for Docsify users

**Comment by sy-records** [comment]
For website SEO, we need `Static HTML Generation`. 👍🏻

`ssr` not working, like docsifyjs/docsify-ssr-demo#3

**Comment by anikethsaha** [comment]
It is a candidate for `v5`.

**Comment by jhildenbiddle** [comment]
Thoughts regarding helpers added to #413.

(Apologies in advance for the lengthy post.)

**Comment by anikethsaha** [comment]
There are few issues with static site generation as we support plugins which kind of does a lot (search bar, pagination etc.). without dom, we cant do it. I am thinking of having `jsdom` to run the plugins in node but still, I think it won't be consistent.  Need second thought about it and also feel free to suggest some better solution for this.

**Comment by gisforgabriel** [comment]
For running search on a static generated site, a library like https://lunrjs.com/ could be a good option.

An index could be created when running `docsify-cli` and Lunr could power the sidebar search instead.

It would probably not be as performant or sophisticated as DocSearch, but it would offer a "proper" static experience - probably the kind of compromise that people who would be interested in the SSG option would prefer (if they're anything like me 😉).

That said, having third party search as another option would also be cool 👍

**Comment by Jacky2** [comment]
I don't know if I can display a floating anchor navigation in each markdown file, like gitbook plugin `gitbook-plugin-anchor-navigation-ex`

**Comment by anikethsaha** [comment]
@Jacky2 you can do it by creating a plugin. please ask questions in a separate issue or in gitter.

**Comment by trusktr** [comment]
Is there an issue tracking `3. Better executable code syntax in MD`?

**Comment by trusktr** [comment]
@anikethsaha I converted some of the above into their own issues, so that we can track them in the 5.0 project board. I assigned you to them just so you're aware / triage.

**Comment by trusktr** [comment]
I updated the issues, and I gave them all labels like `PoC Welcome`, `PR Welcome`, `needs discussion`, etc, to match what we had here. It will be easier to manage it that way, and to have separate conversations in each one while also seeing the respective cards inside the [5.0! project board](https://github.com/docsifyjs/docsify/projects/2).

**Comment by jhildenbiddle** [comment]
Another v5 feature we should consider is tweaking the docisfy plugin architecture to be more resilient. This warrants further discussion, but here are two ideas worth considering:

1. Provide a docisfy plugin "starter" or a sample repo to use as a starting point.

   This would make life much easier for the community and help enforce acceptance criters (below).

1. Define acceptance criteria for all docsify plugins.

   This is critical for docsify because unlike static sites, a docsify-powered site requires Javascript to render content. If a docsify plugin throws an error, it is almost certain that site functionality will be broken. 

   Here are a few idea for acceptance criteria:

   - Specify the version of ECMAScript plugin developers should target. For docsify v4.x, ES5 is the required target to ensure IE11 support. This means dev must either author their plugin with ES5 syntax or transpire their code from ES6+ to ES5. For docsify v5, we'll have to look at our supported browser list to determine the appropriate ECMAScript version to target.
   - Plugin code must be wrapped in a `try { ... } catch(err) { ...}` statement to prevent a plugin error from breaking a site. 
   - Plugins must make their version number accessible to other plugins for interoperability. Docsify addons like [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) and [docsify-tabs](https://jhildenbiddle.github.io/docsify-tabs/) already do this by adding an object to the global `$doscify` object (`$docsify.tabs` and `$docsify.themeable`) with a `value` key and value. The goal is to allow both docsify and other plugins to determine which plugins are active and, if necessary, modify their behavior as needed.
   - Plugins must specify a compatible docsify version to prevent breaking sites when a new version of docsify is released. For example, consider a v4 site that is configured to load the latest version of docsify and multiple plugins. If docsify v5 is released using the same URLs, the v4 site will automatically be "upgraded" to v5 but will likely break as a result of trying to load v4 plugins. This safeguard would allow docsify (or the plugin itself) to determine if it is safe to run the plugin before doing so, which would at least allow the site to load and function properly (albeit without incompatible plugin functionality). This wouldn't be necessary if users locked their docsify, theme, and plugin CDN URLs to a major version (see #780), but since they don't a safeguard like this is necessary.

Just some ideas to get started.

**Comment by jthegedus** [comment]
@jhildenbiddle re 1: I have a plugin template repo I have yet to publicise. I will see about moving it to this org and then we can iterate on it.

**Comment by anikethsaha** [comment]
@jhildenbiddle this is really an awesome suggestion. It would make the plugin integration much more strong and simple.

May be we should extract this suggestion into a new issue.

**My 2 cents** ⬇️

Also, I am thinking of creating a wrapper function something like this `createDocsifyPlugin` function that needs to be returned from the plugin. It will accepts the following data

```ts
interface PluginMetaI {
  version: String;
  docsifyVersion: String;
  polyfillURL?: String;
  definition(hook: Object): void;
  pluginDocsURL?: string;

  // SOme more meta datas,/
}

const createDocsifyPlugin = (PluginData: PluginMetaI): Promise<void> => {
  const { version, docsifyVersion, polyfillUrl, definition } = PluginData;

  // some validation of the datas
  // like loading the polyfill

  // ...

  return new Promise((res, rej) => {
    try {
      res(definition(hook));
    } catch (err) {
      rej(err);
    }
  });
};

export default createDocsifyPlugin({
  version: "4",
  docsifyVersion: "4.11.0", //minimum this version is required.
  definition: hook => {
    hook.beforeEach(function() {});
    // ...
  }
});
```


`createDocsifyPlugin` will be a global function I guess so that inline plugins can be returned as well. 
I used `promise` so that we can handle the async and errors better. 


This is just an example I am thinking of the implementation. We can discuss this for a better approach.

**Comment by jhildenbiddle** [comment]
Plugin / wrapper discussion moved to #1209.

**Comment by EternalDeiwos** [comment]
@anikethsaha You mentioned possibly using markdown-it as the markdown parser in #823 -- is this still being considered because that would be fantastic. It would be really great to have a pluggable parser.

**Comment by trusktr** [comment]
Rather than try to pile a loner of things for a huge release, which we don't have time for, let's release feature when they make a lot of sense, for now.

None of the major bullet points listed in the original post are breaking changes, but feature additions, which don't require a breaking change.

If you we an idea for any change that improves Docsify (apart from a rewrite), we can make an issue or discussion for it, then a pull request if we think the change is worth it, including the appropriate version bump for it whether it is a patch, minor, or major.

By following this approach, we can keep making progress and not stalling a bag full of ideas for one huge major version bump. All of the original points can technically be added in v4.

As a general rule, let's try to keep backwards compatibility as much as we can.

So, I will close this, and let's open specific topics, and try to avoid breaks if possible unless something _needs_ to change to improve end users experience.

**Comment by trusktr** [comment]
I forgot to mention, after getting things moving and making meaningful changes and bumping as necessary, including major bumps, we will be in better shape to stabilize and have less major bumps.

We should publish a nice migration log that makes it easy for people to update. Three.js follows the above approach, and this is what their migration log looks like:

https://github.com/mrdoob/three.js/wiki/Migration-Guide

Let's take inspiration from this, and move forward.
