### ISSUE TITLE
Please update the documentation on how the sidebar / pagination work.

### ISSUE THREAD

**Issue by joetidee** [docsifyjs/docsify#1083]
Currently, there seems to to be very little instruction on how/why certain combinations of `_sidebar.md` files and folder structures make the sidebar navigation and pagination work.

For example, if my `_sidebar.md` file contains this:

```
- **Services**
    - [Getting Started](services/getting-started.md)
    - [Running Service Locally](services/running-services.md)
```

and my folder structure is this:

```
/services
  _sidebar.md
  index.md
  getting-started.md
  running-services.md
```

the pagination and menu structure works fine. But there is no explanation to why this works. If I move `.md` files into sub-folders, pagination doesn't work. If I simply have...

`- [**Services**](services/index.md)`

then pagination does not appear and the sidebar no longer shows the sub-pages. It is quite difficult to know where to place files and what to put into the sidebar to try and get a solution whereby the sidebar can auto-generate itself correctly and the pagination work as expected.

**Comment by trusktr** [comment]
> a solution whereby the sidebar can auto-generate itself correctly

I don't think this is possible at the moment, because the website does not crawl the file system. Docsify is built for a static file server by default, and a static website can not crawl for files because it can not get an index of files in a standard way (some servers provide indices, but it is non standard). So, you have to explicitly define what is in your sidebar. Maybe for SSR and static site generation we can have an auto-generated sidebar feature.

What I believe it currently does is it looks for `_sidebar.md` in the current folder, and uses that, otherwise falls back to the one configured in `$docsify` config, or similar. But you still have to populate those files.

So when you have only `- [**Services**](services/index.md)`, that's the only thing it will show. There's no magic, unless I missed it.

I agree, let's make the docs more clear. :+1:
