### ISSUE TITLE
Docsify not working in IE 11

### ISSUE THREAD

**Issue by Ajaysankaran** [docsifyjs/docsify#1420]
Whenever i try to load docsify url in IE, i am getting an error, " Object doesn't support property or method 'repeat' "

Details:
- OS: Windows 11 
- Node.js version: 10
- npm/yarn version: 6
- Browser version: IE 11
- Docsify version: 4.4.1

Is there any other configuration i need to do?

**Comment by sy-records** [comment]
Can you provide more detailed information?
Try again with the latest released version?

**Comment by Ajaysankaran** [comment]
It is resolved now. I had to keep a polyfil in index.html to make it work. 
I have one more query. How do i get specific content from the pages? i am trying to create a plugin that will convert the text to speech in docsify. Here i want to get a specific content from the md file

**Comment by sy-records** [comment]
```js
     hook.beforeEach(function(content) {
        // Invoked each time before parsing the Markdown file.
        // ...
        return content;
      });
```

`content` is the content of each MarkDown file, you can do what you want with it.

**Comment by Ajaysankaran** [comment]
I have tried this and this will get executed on load. What i wanted is to provide a button. On click of that, i would like to get the specific content and start the text to speech conversion.Is something like this possible in Docsify?

**Comment by sy-records** [comment]
You can try to manipulate the DOM

https://raw.githubusercontent.com/docsifyjs/docsify/develop/docs/themes.md

**Comment by georgeOsdDev** [comment]
@sy-records 
`Object doesn't support property or method 'repeat'` is raised from marked.
https://github.com/markedjs/marked/issues/1771

v4.11.4 work with IE11 but latest(v4.11.6) release does not work with IE11 due to this error.
Docsify v4.11.4 use `"marked": "^0.7.0",` https://github.com/docsifyjs/docsify/blob/v4.11.4/package.json#L61
Docsify v4.11.6 use `"marked": "^1.1.1",` https://github.com/docsifyjs/docsify/blob/v4.11.6/package.json#L60

Please release new stable version with #1425

**Comment by sy-records** [comment]
Thank you for your feedback, we will release it as soon as possible. @georgeOsdDev
