### ISSUE TITLE
Scroll bar pulled to the bottom directory display problem like picture

### ISSUE THREAD

**Issue by wudidehuangtiandi** [docsifyjs/docsify#1699]
![image](https://user-images.githubusercontent.com/54608929/147617538-30b9092b-9fe6-4dea-acbf-cd3b0c687f2f.png)

**Comment by wudidehuangtiandi** [comment]
It seems unreasonable to switch directories only when the title content occupies a full page

**Comment by trusktr** [comment]
This is a problem common in automatic navigation link highlighters, especially when the last content is smaller than the view height.

How do you propose to solve it?

**Comment by wudidehuangtiandi** [comment]
i don,t know baby 。Think about it. It's true。Let me know when there's a better plan

**Comment by trusktr** [comment]
The reason it happens in your screenshot is because the bottom section is _almost_ tall enough, but because it is not, the algorithm still thinks the previous section is in view.

What will we do if there are multiple small sections at the bottom?

Maybe we highlight based on mouse/touch area too.

Maybe it needs an update so that it detects which section is the most in view and/or centered on screen?
