### ISSUE TITLE
sidebar not aligned between file and folder classes

### ISSUE THREAD

**Issue by DanielYWoo** [docsifyjs/docsify#1758]
#### Steps to reproduce
create a sidebar
```
* Whatever
  * [Home](/)
* User Guides
  * [Setup Development Environment](/_user-guide/setup/)  
```
It works perfectly. Now change it to
```
* [Home](/)
* User Guides
  * [Setup Development Environment](/_user-guide/setup/)  
  * [Microservice with REST APIs is dead simple](/_user-guide/platform-lightweight-rest/)
```
The Overview has a different class and cannot be displayed correctly.
![image](https://user-images.githubusercontent.com/514417/155501072-f297a9ab-e801-4f0b-a890-0d1ca24bf708.png)

This is because the class is different:
![image](https://user-images.githubusercontent.com/514417/155501271-dd8528a9-6fcc-4dff-9747-e6e606e4836d.png)

#### What is current behaviour
an item as file or folder behave differently.

#### What is the expected behaviour
both file and folder should behave the same.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS:  OSX Monterey
- Node.js version: N/A
- npm/yarn version: N/A
- Browser version: Chrome  97.0.4692.99 (Official Build) (x86_64)
- Docsify version: latest on CDN
- Docsify plugins: N/A

#### Please create a reproducible sandbox 
[code sandbox demo](https://codesandbox.io/embed/dreamy-nobel-3qyr81?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Koooooo-7** [comment]
Hi, it seems this issues of `docsify-themeable`.
```js
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple.css"
/>
```
@jhildenbiddle  I think you may give a hand here.  😃

**Comment by jhildenbiddle** [comment]
@DanielYWoo --

@Koooooo-7 is right: this is a [docsify-themeable](https://github.com/jhildenbiddle/docsify-themeable) issue, not a docsify issue.

FWIW, I'm not seeing the same issue...

Markdown:

```
* Whatever
  * [Home](/)
* User Guides
  * [Setup Development Environment](/_user-guide/setup/)  
``` 

<img width="272" alt="CleanShot 2022-03-24 at 17 29 45@2x" src="https://user-images.githubusercontent.com/442527/160020895-241d758a-4451-4044-95f0-cf5592466da1.png">

Markdown:

```
* [Home](/)
* User Guides
  * [Setup Development Environment](/_user-guide/setup/)  
  * [Microservice with REST APIs is dead simple](/_user-guide/platform-lightweight-rest/)
```

<img width="272" alt="CleanShot 2022-03-24 at 17 29 20@2x" src="https://user-images.githubusercontent.com/442527/160020950-3b67dbc1-667e-4559-9ae4-a5057381f2b3.png">

If you are trying to create section, you can do so by making section headings **bold**:

Markdown:

```
- **Whatever**
  - [Home](/)
- **User Guides**
  - [Setup Development Environment](/_user-guide/setup/)
```

<img width="272" alt="CleanShot 2022-03-24 at 17 30 19@2x" src="https://user-images.githubusercontent.com/442527/160021092-4607edaa-ee43-4657-8ca6-3962462e9d82.png">

Closing since this is not a docsify issue and I am not seeing the same output. Feel free to create a new issue in the [docsify-themeable](https://github.com/jhildenbiddle/docsify-themeable) repo if you would like to discuss further.

**Comment by DanielYWoo** [comment]
thanks @jhildenbiddle I will create an issue there. 
BTW, open the sandbox link, click the nav bar, how does it look on your computer?
