### ISSUE TITLE
When I write a link to a network drive in a markdown document, it is not recognized correctly and I cannot go to the link.

### ISSUE THREAD

**Issue by sheepwng** [docsifyjs/docsify#1991]
## Feature request

When I write a network drive link such as `file:///10.0.0.1/example.html` or `\\10.0.0.1\example.html` in a markdown document, it is not recognized correctly and I cannot go to the link.
Or is there a workaround?
I really need this kind of functionality.

#### What problem does this feature solve?
I would like to be able to open the following link:
```
file:///10.0.0.1/example.html

\\10.0.0.1\example.html

[link1](file:///10.0.0.1/example.html)

[link2](\\10.0.0.1\example.html)
```

#### What does the proposed API look like?
Not API.

#### How should this be implemented in your opinion?
I would like to be able to write a network drive link in the markdown so that it is recognized as an external link and the link is opened.

#### Are you willing to work on this yourself?
No.

**Comment by Koooooo-7** [comment]
Hi @sheepwng , IIUC, you wanna load the local file via file protocol even not ftp, but you already raise a server of docsify locally since you can visit it on localhost.
It is contradiction that loading a local file directly via the server. and browser gonna block this option either.

You need move those local files to "the server", which means they should related to the server root path or you can store them as static resources on nginx (or other proxy server ) if you gonna deploy it.
