### ISSUE TITLE
in an environment without internet access.

### ISSUE THREAD

**Issue by sogadm** [docsifyjs/docsify#2252]
#### Problem or desire

I am using Docsify, a runtime documentation generator, in an environment without internet access. Currently, Docsify relies on certain JS and CSS files that are fetched from the internet. This poses a problem in my use case.

#### Proposal

I propose that the developers provide a set of static files for all the JS and CSS dependencies that Docsify needs. This way, Docsify can be used in environments without internet access.

#### Implementation

The developers could bundle all the necessary JS and CSS files into a downloadable package. This package could then be hosted on the same server as the Docsify instance, allowing Docsify to fetch its dependencies from the local network instead of the internet.

**Comment by trusktr** [comment]
Hello @sogadm, Docsify already provides those files. You can download those files, place them in your local project, and update the URLs in your app to use the local files.

F.e. instead of

```html
<script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js"></script>
```

you can import a local version:

```html
<script src="./docsify.min.js"></script>
```

You can access any URL, and download it in your browser. For example:

https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js

right click, save as.

You can run "view source" in your browser to see the HTML of Docsify site, and you can see all the URLs there, and you can save them all, for example.

You can also download them from the GitHub repo here.

You can also install them with `npm` (Node.js package manager) if you install Node.js. Then you can:

```html
<script src="./node_modules/docsify/lib/docsify.min.js"></script>
```

Feel free to open new question if more help needed.
