### ISSUE TITLE
Upon Navigating to the 'Inside' Solid Square bullet , the Narrator did not Announce on the Solid Square.

### ISSUE THREAD

**Issue by msftedad** [docsifyjs/docsify#2282]
#### Steps to reproduce

1. Navigate to this link [First Level Child (zorana-jankovic.github.io)](https://zorana-jankovic.github.io/example/#/start)
2. Navigate to inside solid square bullet. 
3. Observe the narrator's announcement.

#### Current behaviour

Upon Navigating to the Solid Square, the Narrator did not Announce on the Solid Square.

#### Expected behaviour

Upon navigating to the solid square, the narrator should announce on the solid square.
Additional notes 

#### Other relevant information

- Docsify version: 
cli version: 4.4.4

<!-- Please provide the following information if relevant to the issue.
Your OS: OS 23H2 (Build 25951.1010)
Node.js version: node --version - v18.17.0
npm/yarn version: yarn --version - 3.2.1
Browser version: Edge Dev Version 119.0.2151.2 (Official build) dev (64-bit)

#### Please create a reproducible sandbox

 [First Level Child (zorana-jankovic.github.io)](https://zorana-jankovic.github.io/example/#/start)

#### Mention the docsify version in which this bug was not present (if any)-No

**Attachments:**

![204941_Docsify-Web](https://github.com/docsifyjs/docsify/assets/93735775/a53bb5ea-b965-4da7-8987-a029d7372c94)
[Solid square screen reader attachment.webm](https://github.com/docsifyjs/docsify/assets/93735775/9a4023ee-bcde-4d27-a438-1873ba143816)

**Comment by jhildenbiddle** [comment]
Hi, @msftedad.

I am unable to reproduce this issue using macOS [VoiceOver](https://support.apple.com/guide/voiceover/welcome/mac):

https://github.com/docsifyjs/docsify/assets/442527/487fc9b0-e44b-4ffa-b6a6-c70700fb46cd

I have also confirmed that Docsify's HTML output is as expected:

```html
<ul>
  <li>First list item
    <ul>
      <li>Inside</li>
      <li>Inside
        <ul>
          <li>Inside</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

These two things lead me to believe this is an issue specific to Windows Narrator. One suggestion is to perform a similar test using Narrator on a separate HTML page to verify that Narrator is able to handle deeply nested unordered lists as expected.

**Comment by msftedad** [comment]
Hi @jhildenbiddle, Issue was reported on edge (windows) but not repro detail was provided on MacOS. could you please check with Window and edge.
Can you please reopen this issue.Thanks

**Comment by jhildenbiddle** [comment]
@msftedad --

Testing with VoiceOver was intentional. The goal was to determine if the issue described affects screen readers in general or Windows Narrator. 

The video demonstrates the site you linked to working as expected with a different screen reader utility (VoiceOver on macOS). The HTML generated by Docsify has been verified to be semantically correct, well-structured, and without additional attributes that would impact screen reader behavior. As a result and as stated:

> These two things lead me to believe this is an issue specific to Windows Narrator. 

Windows Narrator is one of many screen readers available. We cannot test with every screen reader nor do we want to implement fixes for specific screen reader issues. This is why I suggested:

> One suggestion is to perform a similar test using Narrator on a separate HTML page to verify that Narrator is able to handle deeply nested unordered lists as expected.

By removing Docsify from the equation you can determine conclusively if the issue is related to Windows Narrator or Docsify.  If Windows Narrator is the cause, then a fix won't come from Docsify. 

> Can you please reopen this issue

I am happy to re-open the issue if/when there is reason to believe that the issue described is related to Docsify. You can accomplish this by testing Narrator outside of Docsify as described above and/or using alternative screen readers such as JAWS, NVDA, etc.
