### ISSUE TITLE
Direct links doesn't open when for routerMode: 'history'

### ISSUE THREAD

**Issue by dmytrodanylyk** [docsifyjs/docsify#238]
When I set `routerMode: 'history'` and open direct link `http://localhost:3000/buttons` I see error page with text `Cannot GET /buttons`. 

When I open `http://localhost:3000` and click on buttons, it navigate me to `http://localhost:3000/buttons` and render it correctly. Any idea how to fix this?

**Comment by hanzichi** [comment]
same issue

**Comment by hanzichi** [comment]
it seems it has not been solved for over one year?? If so, just remove the configuration from the docs

**Comment by hanzichi** [comment]
my fault, we should set the server side, see <https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations>

**Comment by jsmedmar** [comment]
@hanzichi, do you know how to configure for github pages?

**Comment by hanzichi** [comment]
@jsmedmar I think you can only use hash mode for github pages

**Comment by JudeAntony** [comment]
@dmytrodanylyk @jsmedmar any idea how can I get this working while running in development mode using docsify serve where I do not have any server side configurations.

**Comment by arvindanta** [comment]
@JudeAntony Did u find a way to run in dev mode ?

**Comment by ASaiAnudeep** [comment]
@jsmedmar to use **history** router mode in github pages, create `404.html` file and copy the contents of `index.html`. 
Example - [reference](https://github.com/pactumjs/pactumjs.github.io),  [demo](https://pactumjs.github.io/)

**Comment by mupfdev** [comment]
Brilliant little hack, thank you. This should be pointed out in the official documentation.

**Comment by trusktr** [comment]
Here is the 404.html redirect trick for GitHub Pages. But note, without providing a sitemap to Google, Google will not index those pages because it ignores pages with a 404 status by default.

https://github.com/rafgraph/spa-github-pages

If you're using a static server, there may be a rewrite rule you can set to forward all requests to a particular file. F.e. with Vercel, instead of the 404.html trick, you can forward to /index.html internally, and the browser will not receive a 404 code. For Vercel, the vercel.json might look like so:

```js
{
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}
```
