### ISSUE TITLE
Search file configuration

### ISSUE THREAD

**Issue by LIGMATV** [docsifyjs/docsify#2409]
## Feature request

#360  Search file configuration

#### Problem or desire

I want to have a configuration to including all files in search result.

#### Proposal

See title.

#### Implementation

```diff
{
search : [
+      '/',            // => /README.md
+     '/zh-cn',      // => all the files in /zh-cn folder
+     '/us-en/a*'  // => all the files that name start with 'a'
    ]
}
```

**Comment by sy-records** [comment]
If you don't use auto mode, you need to manually define the paths you need to search for in search.paths.

If you need to support searching content in multiple languages at the same time, it needs to be added to the sidebar in order to generate an index.

The search starts with a certain character and specifies a directory, which is not currently planned to be supported.
