### ISSUE TITLE
Change sidebar css class

### ISSUE THREAD

**Issue by cristijora** [docsifyjs/docsify#384]
Trying to figure out if it's possible to change the sidebar class without any side effects.
My current approach is something like this:

```js
plugins: [
      function (hook, vm) {
        hook.mounted(function () {
          var sidebar = document.querySelector('aside.sidebar');
          sidebar.classList.remove('sidebar');
          sidebar.classList.add('docsify-sidebar');
        })
      }
    ]
```

I have the css for docsify internally in my project and can modify it with no issues, however I get 
```js
docsify.min.js:1 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at l (docsify.min.js:1)
    at I (docsify.min.js:1)
    at oe.e._bindEventOnRendered (docsify.min.js:2)
    at oe.e._renderSidebar (docsify.min.js:2)
    at docsify.min.js:2
    at Object.then (docsify.min.js:1)
    at ne (docsify.min.js:1)
    at h (docsify.min.js:2)
    at docsify.min.js:2
    at Object.then (docsify.min.js:1)
```
when trying to navigate from one page to another in the sidebar

**Comment by trusktr** [comment]
Sorry that you hadn't received a reply since 2018! Your example doesn't use `querySelectorAll`, but it uses `document.querySelector`, and `document` can never be `undefined` while in a browser.

The code itself looks fine. 

The project is being more actively maintained lately; feel free to re-open an issue if still needed.
