### ISSUE TITLE
Custom HTML for cover page

### ISSUE THREAD

**Issue by soulfly** [docsifyjs/docsify#481]
Currently, to build a cover page use use md file https://docsify.js.org/#/cover
Is it possible to build completely custom cover page in HTML?

**Comment by dmed256** [comment]
It's in the roadmap:

 - https://github.com/QingWei-Li/docsify/projects/1

**Comment by soulfly** [comment]
Thanks, will monitor it then

**Comment by kjcpaas** [comment]
@soulfly For now, I am able to use custom html by the following:

In index.html:

```javascript
window.$docsify = {
  // other configs...
  coverpage: '_coverpage.html'
}
```

In `_coverpage.html`:

```html
<h1>My docs title </h1>

Other content
```

I just included my custom CSS in `index.html` to format the coverpage.

If you want to take advantage of the background image you have to set it as the last (?) image in the coverpage html like this:

```html
Other html content here

<p><img src="_media/bg.jpg" data-origin="_media/bg.jpg" alt="background"></p>
``` 

`data-origin`is important because that's how docsify gets the coverpage background image. ref: https://github.com/QingWei-Li/docsify/blob/master/lib/docsify.js#L3861

**Comment by trusktr** [comment]
Seems like this is fully supported. Just set `coverpage` to a file that has markdown (and note, markdown can also contain HTML, so use HTML in the file if you want).
