### ISSUE TITLE
Looking for Maintainer

### ISSUE THREAD

**Issue by QingWei-Li** [docsifyjs/docsify#603]
As you can see, this project is now rarely maintained. First, I think the project is basically stable. Second, I am busy recently.

So I am looking forward to joining the docsify team to help refine and fix the issue.

😇

**Comment by jhildenbiddle** [comment]
What is the current maintainer status of docsify?

After investing in docsify by creating [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) and [docsify-tabs](https://jhildenbiddle.github.io/docsify-tabs/), it would be disappointing to learn that the project is no longer maintained. Some signs of life would go a long way towards motivating others to sign on as maintainers (myself included) if that's what's needed.

**Comment by QingWei-Li** [comment]
Currently no maintainer. Do you want to try?

**Comment by jhildenbiddle** [comment]
Perhaps as a supporting team member, but not as the sole maintainer. 

As I mentioned above, seeing some signs of life—even if it's just base-level maintenance like merging PRs and addressing only critical fixes—would help motivate myself and others to lend a hand.

If you were willing to commit to base-level maintenance of the project moving forward, I would be willing to assist with the effort. We can work together to define exactly what "base-level" means and how to handle existing issues and PRs, as well as incoming issues and feature requests. 

Given that there are *zero* maintainers now and no work is being done, putting a plan in place that involves even just a few hours per month would breath some life back into the project.

**Comment by cheng-kang** [comment]
I'm interested in joining the team 🙋‍♂️ 

Docsify is amazing!

**Comment by QingWei-Li** [comment]
@cheng-kang 🤩Cool

Sorry for late reply... 
I have invited you to join the organization, then if you have any questions you can contact me via email(cinwell.li#gmail.com) or telegram(cinwell_li).

**Comment by jthegedus** [comment]
@QingWei-Li I'm in a similar position as @jhildenbiddle in that I'm making a variety of plugins and have just started using docsify for all the things. I would like to help where possible as a supporting member (not sole maintainer) as I want docsify to thrive!

**Comment by timaschew** [comment]
@jhildenbiddle 

> If you were willing to commit to base-level maintenance of the project moving forward, I would be willing to assist with the effort. We can work together to define exactly what "base-level" means and how to handle existing issues and PRs, as well as incoming issues and feature requests.

I actually asked a similar questions, the answer is quite short ;)
https://github.com/docsifyjs/docsify/issues/754#issuecomment-456649443

**Comment by timaschew** [comment]
@QingWei-Li @jhildenbiddle @jthegedus @cheng-kang 

I would like to discuss which policy we want to drive for docsify.  
For instance: I've created [this pull request](https://github.com/docsifyjs/docsify/pull/776) 11 days ago and assigned the core members to it. I still got no feedback yet.  

Are too busy to check? That means either we wait until someone has time or can I merge my own pull request? If the latter, then we should define some rules and add them probably into the CONTRIBUTING:md
For instance: provide tests, explain which problem is solved, etc.

What do you think?

**Comment by jthegedus** [comment]
@timaschew I'm not sure who is part of the group `core`, or how to check.

Given I have not seen a post from @QingWei-Li I assume they are still looking for maintainers. I'm certainly open to helping, but don't have the skill to be a sole maintainer at this time (open to guidance).

I like the requirements that repos have where you need at least 2 reviewers before merging. DefinitelyTyped has cool tooling that automatically pings anyone who has previously edited the code that is being changed, so that people who know the context of the changes can review it. Maybe we consider adding something like that here. (I have not set it up before, but it works well on their repo - https://github.com/DefinitelyTyped/dt-review-tool)

I think we should definitely review the rules and guidance in the Contributing guide and the GitHub templates. I have spent some time doing that with other projects recently so happy to give that a go.

**Comment by timaschew** [comment]
Oh, actually I was expecting to see you @jthegedus and @jhildenbiddle in the core team, but you are not part of it (yet).

Members are currently:
- QingWei-Li 
- cheng-kang
- timaschew (me)

Are you okay if I add you (@jthegedus and @jhildenbiddle) to it, so it will be easier to reach out to you all via `@core`.

>  I'm certainly open to helping, but don't have the skill to be a sole maintainer at this time (open to guidance).

Sure, that's enough for now.

> I like the requirements that repos have where you need at least 2 reviewers before merging. 

But this only works if the feedback delay is short. So waiting longer than a week for instance doesn't work/scale. I mean it doesn't help I think if people are busy with other stuff or having other priorities – and that's fine. But in this case we shouldn't expect to get feedback from them.

**Comment by timaschew** [comment]
@QingWei-Li  I wanted to add @jthegedus and @jhildenbiddle to the core team but I can't. Can you do that or give me maintainer permissions, please?

**Comment by jhildenbiddle** [comment]
Hey @timaschew. Apologies for not responding sooner.

Happy to take on a supporting role, and I agree that getting some rules in place for how the project will be maintained moving forward is an important step.

I like the idea of two reviews before a merge, especially early on and with so many new core team members. If the requirement becomes burdensome, we can reevaluate. The exception to the rule would be @QingWei-Li, obviously.

**Comment by timaschew** [comment]
@QingWei-Li do you consider to give me maintainer permissions for the docsify organization on GitHub and publish permissions on npm for docsify?

**Comment by timaschew** [comment]
Sorry but this doesn't work for me (and I guess even in general).  
A community driven project cannot delay some actions (like reacting on super critical issues, by fixing them or merging contributed fixed in and publishing a fixed version) just because the main author is not sharing permissions to people which offer to contribute and maintain the project and is super busy at the same time with other stuff.

I'm going to fork this project and publish it under **doczify**.  
If anybody wants to join leave a comment on [doczify](https://github.com/doczifyjs/doczify/issues/1)

**Comment by jhildenbiddle** [comment]
@timaschew --

I feel your frustration. The maintainer's unwillingness to provide a base level of support for the project is why I've resigned myself to only creating issues (because I want to see the project improve) rather than fixing them myself (because the project feels almost abandoned at this point). It's too bad, because with a few enhancements (pre-rendered static content being the most important, IMHO) I think docsify could be in a very strong position against some heavyweight competitors.

A project with 9000+ stars is a success by any measure. It would be truly unfortunate if people dedicated to the ongoing success of the project were forced to fork instead of allowing them to contribute directly to docsify--especially after asking for people to sign on as maintainers of the project.

Thanks for diving in and trying find some traction, @timaschew.

@QingWei-Li -- Can we resolve this issue granting @timaschew maintainer permissions so we can avoid forking?

**Comment by upupming** [comment]
I really hope `docsify` can always improve, there are so many issues need to be resolved now. A comparison of docsify and vuepress:
- veupress: 98 open issues, 829 closed issues
- docsify: 159 open issues, 399 closed issues
Without support from the maintainers, people may lose confidence in docsify.

**Comment by timaschew** [comment]
Continue the discussion here from #802 because it's not really related to the pull request

> First of all, I have to apologize.
>
>I haven't read the issues for a long time and haven't noticed your email. I may have to leave this project.
>
>I have promoted @timaschew to owner and hope that you can continue to maintain docsify.
>
>This is my last contribution to docsify. If you feel that there is no problem, then I will release 5.0. And give the release permission to your.
>
> @timaschew
If you need permission to post, please let me know your npm account.

>I haven't read the issues for a long time and haven't noticed your email. I may have to leave this project.
>This is my last contribution to docsify.

No worries ;) But it's a pity that you're leaving.  
Let's see how far we can bring docsify ;)

Please add [jhildenbiddle](https://www.npmjs.com/~jhildenbiddle) and [timaschew](https://www.npmjs.com/~timaschew) for the npm modules.

**Comment by QingWei-Li** [comment]
@timaschew 

Now you have the publishing permission for [docsify](//npm.im/docsify) [docsify-cli](//npm.im/docsify-cli)  [docsify-server-renderer](//npm.im/docsify-server-renderer)

**Comment by timaschew** [comment]
@jhildenbiddle you've an invitation for the core team.

**Comment by timaschew** [comment]
@QingWei-Li How do I deploy new changes to https://docsify.js.org ?

**Comment by QingWei-Li** [comment]
Merge code to master and run `npm run pub`

Anton Wilhelm <notifications@github.com> 于 2019年4月14日周日 06:08写道：

**Comment by timaschew** [comment]
The **release.sh** is just deploying docsify to npm.
But how are the html and md files deployed?

**Comment by QingWei-Li** [comment]
Just merge code to master branch. The docs website now contains now content.

Anton Wilhelm <notifications@github.com> 于 2019年4月14日周日 17:09写道：

**Comment by timaschew** [comment]
But that means if I merge md files (docs) to master they are immediately updating docsify.js.org but the md files which describes a feature are not published to npm. 

To keep docs and code aligned that means I need to publish a new version every time I merge something to master?

**Comment by QingWei-Li** [comment]
The best way is to create a develop branch, only merge the branch to master when the new version is released.

**Comment by timaschew** [comment]
Yes, I was thinking the same. Thanks.

**Comment by Gab0o777** [comment]
Hey guys, first of all, awesome project you have here and would be a shame to see it die.  I find the current issues really important for development and am very interested in joining the team and help contribute. What's the current state of the project?

**Comment by upupming** [comment]
@Gab0o777 Thanks, I am really glad to hear that!
Let me clarify the situation now. @QingWei-Li is the creator of this project, but he is too busy to maintain this project, and now @timaschew has taken over it. They have proposed discussed the v5.0 roadmap at https://github.com/docsifyjs/docsify/issues/657 before, there are many nice features and good considerations. But they found there are too many issues need to be reasonably answered and repaired., so maintainers are working at #823 now.
The major pity is that the community hasn't grown strong enough before the creator left, and now there are not many people can go beyond @QingWei-Li  as far as I can see.

So for my bad English, and I really hope this community can be live again!

**Comment by Koooooo-7** [comment]
It's not a good news...

Indeed ,we  should not let  the awesome project  be abandoned.
The  9000+ starts  indicates that  the project is powerful .
Docsify is amazing !

Although  I'm not skilled  in  JS ,  I would like to help contribute within the scope of my ability.

@upupming  
Hey  bro , Why Not You ! :muscle:

**Comment by upupming** [comment]
@Koooooo-7 Thanks for your encouragement, but I'm not very experienced, either. I am still learning front end development and willing to contribute to docsify~

**Comment by timaschew** [comment]
FYI: I am currently on vacation for some weeks. So I won’t contribute so much I guess.
But from June I will have lot of time to work on docsify.

**Comment by filipgoc** [comment]
I'm not even using Docsify, but I am happy it's not dead yet. Kudos to everyone here involved for keeping the conversation civil and productive and ultimately reaching a positive outcome (light at the end of the tunnel).

**Comment by raydied4** [comment]
hope it will be better。

**Comment by TheGreenToaster** [comment]
Love this project but it looks like it is stagnating again. 
I am not skilled in maintaining a project but I am willing to do whatever I can to keep the project going. So let me know if there is anything i can do @timaschew

**Comment by timaschew** [comment]
I've planned to use docsify at work and my idea was to contribute most work back to this open source project. But since I've realized VuePress is a better fit for our case at work I've stopped using docsify.
Also I had a different expectation regarding my familial circumstances.
So unfortunately I don't have the time which I've expected, neither for docsify nor for any other open source project.

**Comment by jthegedus** [comment]
I too am in the same position as @timaschew . I was using this tool for other projects, thought I would be able to contribute during overlap with work and thought I would have more time in my personal time to put towards this. I was incorrect and cannot devote the amount of time required to maintain this project and the growing # of contributions.

**Comment by felangel** [comment]
I'm using docsify for my [open source documentation](https://felangel.github.io/bloc) and would love to help maintain it if the original maintainers don't have the time.

**Comment by timaschew** [comment]
Welcome @felangel, I've invited you to the docsifyjs organization.

**Comment by algobot76** [comment]
I use docsify on a daily basis ([my-cs-notes](https://github.com/algobot76/my-cs-notes)) and I really like it. I don't want this awesome project to go unmaintained. I'm willing to sacrifice some of my free time for the project.

**Comment by egoist** [comment]
Hi @QingWei-Li @timaschew author of https://github.com/egoist/docute here

Seeing so many great projects using Docisfy is really inspiring, I would love to help the team maintain this awesome software! As a result I would probably deprecate Docute too.

**Comment by santoshyadav198613** [comment]
Count me in .

**Comment by Zielak** [comment]
We've just started using docsify in our companies internal projects, and I'm willing to include it in one of my open source projects. I'd love to be part of it to keep it healthy.
I just stumbled on an issue with dependencies in docsify-cli and I could easily make a PR for that.

**Comment by anikethsaha** [comment]
Hi, folks....
First of all, this is really an awesome project and I am using this for one of my projects (https://mern.netlify.com/#/), 
I am willing to chip in here and I think I can help with the docsify-cli as I have some past experience in working with CLIs (webpack-cli, https://github.com/anikethsaha/create-web-app). 
So here, if you guys need help with the CLI , I can provide some 👍

**Comment by anikethsaha** [comment]
cc @QingWei-Li @timaschew @jhildenbiddle

Is there any way to contact you guys apart from github ?

I think we need someone to merge PRs of docsify-cli. as there are quite a good number of security alerts there in the dependencies.

**Comment by felangel** [comment]
@anikethsaha just merged the security PRs from dependabot 👍

**Comment by anikethsaha** [comment]
@felangel are you guys looking for new maintainers ?like is this issue resolved ?

**Comment by felangel** [comment]
@anikethsaha I'm not sure as I only recently joined the organization

**Comment by anikethsaha** [comment]
@felangel okay will wait for others to respond 👍

**Comment by jamesgeorge007** [comment]
@felangel I would love to collaborate on the `docsify-cli` project. Just shooted a couple of PR's :tada:

**Comment by jamesgeorge007** [comment]
@QingWei-Li I would love to collaborate on the `docsify-cli` project. Just shooted a couple of PR's :tada:
