### ISSUE TITLE
documents scroll underneath fixed position header

### ISSUE THREAD

**Issue by activedecay** [docsifyjs/docsify#631]
When clicking documentation links, using a header with a fixed position, the document scrolls underneath the header. What do you think of allowing this offset as a new config value?

inside src/core/config.js:14

    windowYOffset: 0, // some user defined offset is allowed to account for fixed headers

inside `export function initEvent(vm)` at src/core/event/index.js:17

    setWindowYOffset(vm.config.windowYOffset)

now fix up the scroll code a bit in src/core/event/scroll.js:23

    end: el.getBoundingClientRect().top + window.pageYOffset - windowYOffset,

**Comment by saioared** [comment]
Is this feature closed because is scheduled or because you don't feel it usefull?

It would be great to have this, I just change de docsify.js file because I needed this feature. I am not happy of doing it but I have a fixed header and I need it to work good.

Hope you add this on future release.

Thankssss :))

**Comment by anikethsaha** [comment]
I would be happy if someone can submit a PR with this. 

Thanks

**Comment by iskhakov** [comment]
I guess this issue had been fixed in https://github.com/docsifyjs/docsify/pull/1045

**Comment by jhildenbiddle** [comment]
Fixed in #1045.
