### ISSUE TITLE
consider support vue data through config globally

### ISSUE THREAD

**Issue by wizicer** [docsifyjs/docsify#752]
maybe we can change this line of code:
https://github.com/docsifyjs/docsify/blob/1a945d445a636d778b242f9d74af4f72c7d89e16/src/core/render/index.js#L60
to include data from config file, code may like this:
```js
      window.__EXECUTE_RESULT__ = new window.Vue({ data: this.config.vueData }).$mount('#main')
```

**Comment by timaschew** [comment]
We can also pass the whole object:

```js
window.__EXECUTE_RESULT__ = new window.Vue(this.config.vueOptions).$mount('#main')
```

This should be even more flexible, right?

**Comment by trusktr** [comment]
I don't see `vueOptions` or `vueData` anywhere. I'm assuming this is a feature request for a new option.

Seems that the current `new window.Vue().$mount('#main')` feature simply allows us to add some HTML like `<div v-for="item in Array.from({length: 10})">` into the page, but not much else. It is fairly useless without data (besides the simple looping to make duplicating things easier).

The code in that conditional block is very bad. The `executeScript` and `new Vue` calls can execute scripts multiple times haphazardly.

I have a pull request coming for this soon. The change can currently be seen [here](https://github.com/docsifyjs/docsify/pull/1091/files#diff-250dfe7435d59fa33e80765c47190dd5R66), though I will revise it and add unit tests.

**Comment by jhildenbiddle** [comment]
@trusktr -- With #1271 now complete, adding the ability to pass data to Vue instances would be really helpful.

Keep in mind that if we have only one Vue configuration, then that configuration will be shared across all Vue instances that docsify auto-instantiates. We can allow for multiple Vue configurations, accessible using CSS selectors as keys, so that configurations can be applied to individual elements:

```js
window.$docsify = {
  vueData: {
    // Pass this data to elements with id="my-container"
    '#my-container': {
      // ...
    },
    // Pass this data to elements with class="my-container"
    '.my-class': {
      // ...
    },
    // Pass this data to <my-component> elements
    'my-component': {
      // ...
    }
  }
}
```

Since docsify adds the current page name to the `<body>` tag using a `data-page` attribute, users can target page-specific elements as well:

```js
window.$docsify = {
  vueData: {
    // Pass this data to elements with id="my-container" on README.md
    'body[data-page="README.md"] #my-container': {
      // ...
    },
    // Pass this data to elements with id="my-container" on configuration.md
    'body[data-page="configuration.md"] #my-container': {
      // ...
    },
  }
}
```

Thoughts?
