### ISSUE TITLE
SSR example not working

### ISSUE THREAD

**Issue by Meemaw** [docsifyjs/docsify#769]
Hi there,

Is it possible for you to update and extend the SSR example provided in your docs? After following all the steps and trying different things it still doesn't work.

**Comment by timaschew** [comment]
related: #759

**Comment by ColinMaudry** [comment]
> related: #759

#759 is about SS Routing, while this one is about rendering, as SSR Routing is not documented on https://docsify.js.org (AFAIK).

**Comment by ColinMaudry** [comment]
To be more specific, when using https://github.com/docsifyjs/docsify-ssr-demo and trying to configure my project the same way:

```
npm start
```

No error, but localhost:4000 returns a blank page. I think it only looks for `index.html`. Basically, it seems to ignore the SSR configuration.

```
npm run deploy

> docsify-ssr-demo@1.0.0 deploy /home/colin/git/docsify-ssr-demo
> now -p

> Deploying ~/git/docsify-ssr-demo under colinmaudry
> Error! Your version of Now CLI is not supported anymore. Please upgrade to the latest version using `npm i -g now`.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docsify-ssr-demo@1.0.0 deploy: `now -p`
npm ERR! Exit status 1
```

`now` has changed since this demo was made.

**Comment by anikethsaha** [comment]
if anyone wants to add docs for SSR enhancement. Feel free to submit a PR
